routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PostsController@index')->name('top');
Route::resource('posts', 'PostsController', ['only' => ['create', 'store', 'show']]);
// ここです★
Route::get('/thanks', function () {
  return view('thanks');
});
//

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
  protected $fillable = [
    'body',
  ];

  public function post()
  {
    return $this->belongsTo('App\Post');
  }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
  protected $fillable = [
    'title',
    'body',
  ];

  public function comments()
  {
    return $this->hasMany('App\Comment');
  }
}

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;

class PostsController extends Controller
{
  public function index()
  {
    $posts = Post::orderBy('created_at', 'desc')->get();

    return view('posts.index', ['posts' => $posts]);
  }

  public function create()
  {
    return view('posts.create');
  }

  public function store(Request $request)
  {
    $params = $request->validate([
      'title' => 'required|max:50',
    ]);

    Post::create($params);

    return redirect('/thanks');
  }

  public function show($post_id)
  {
    $post = Post::findOrFail($post_id);

    return view('posts.show', [
      'post' => $post,
    ]);
  }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Task;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class TaskController extends Controller
{
  public function index()
  {
    $tasks = Task::latest()->get();
    return view('tasks.index', [
      'tasks' => $tasks
    ]);
  }

  public function store(Request $request)
  {
    $validator = Validator::make($request->all(), [
      'task_name' => 'required|max:255',
    ]);
    if ($validator->fails()) {
      return redirect('/')
        ->withInput()
        ->withErrors($validator);
    }
    $task = new Task;
    $task->name = $request->task_name;
    $task->save();
    return redirect('/');
  }

  public function destroy(Task $task)
  {
    $task->delete();
    return redirect('/');
  }
}

resources/views/common/errors.blade.php
@if (count($errors) > 0)
<!-- Form Error List -->
<div class="alert alert-danger">
  <strong>Whoops!</strong> There were some problems with your input.<br><br>
  <ul>
    @foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Laravel BBS</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
  <header class="navbar navbar-dark bg-dark">
    <div class="container">
      {{-- <a class="navbar-brand" href="{{ url('top')}}"> --}}
      <a class="navbar-brand" href="{{ route('top')}}">
        a part of dアニメストア
      </a>
    </div>
  </header>

  <div>
    @yield('content')
  </div>
</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="ja">

<head>
  <title>Laravel Quickstart - Basic</title>

  <!-- CSSとJavaScript -->
</head>

<body>
  <div class="container">
    <nav class="navbar navbar-default">
      <!-- ナビバーの内容 -->
    </nav>
  </div>

  @yield('content')
</body>

</html>

resources/views/posts/create.blade.php
@extends('layout')

@section('content')
<div class="container mt-4">
  <div class="border p-4">
    <h1 class="h5 mb-4 text-warning">
      リクエストしたいアニメを入力してください。これからの参考にしていただきます。
    </h1>

    <form method="POST" action="{{ route('posts.store') }}">
      @csrf

      <fieldset class="mb-4">
        <div class="form-group">
          <label for="title">
            タイトル
          </label>
          <input id="title" name="title" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}"
            value="{{ old('title') }}" type="text">
          @if ($errors->has('title'))
          <div class="invalid-feedback">
            {{ $errors->first('title') }}
          </div>
          @endif
        </div>

        <div class="mt-5">
          <a class="btn btn-secondary" href="{{ route('top') }}">
            キャンセル
          </a>

          <button type="submit" class="btn btn-primary">
            投稿する
          </button>
        </div>
      </fieldset>
    </form>
  </div>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layout')

@section('content')

<div class="container mt-4">
  <div class="mb-4">
    <a href="{{ route('posts.create') }}" class="btn btn-warning">
      リクエストしたいタイトルはありますか？
    </a>
  </div>
  @foreach ($posts as $post)
  <div class="card mb-4">
    <div class="card-header">
      <span>{{ $post->title }}</span>
      <span class="mr-2">
        投稿日時 {{ $post->created_at->format('Y.m.d') }}
      </span>
      　　　</div>
  </div>
  @endforeach
</div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')
<div class="panel-body">
  @include('common.errors')

  <form action="{{ url('task') }}" method="POST" class="form-horizontal">
    {{ csrf_field() }}
    <div class="form-group">
      <label for="task" class="col-sm-3 control-label">Task</label>

      <div class="col-sm-6">
        <input type="text" name="name" id="task-name" class="form-control">
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <button type="submit" class="btn btn-default">
          <i class="fa fa-plus"></i> Add
        </button>
      </div>
    </div>
  </form>
</div>

@if (count($tasks) > 0)
<div class="panel panel-default">
  <div class="panel-heading">
    Task List
  </div>

  <div class="panel-body">
    <table class="table table-striped task-table">
      <thead>
        <th>Task</th>
        <th> </th>
      </thead>

      <tbody>
        @foreach ($tasks as $task)
        <tr>
          <td class="table-text">
            <div>{{ $task->name }}</div>
          </td>
          <td>
            <form action="{{ url('task/'. $task->id) }}" method="POST">
              {{ csrf_field() }}
              {{ method_field('DELETE') }}

              <button type="submit" class="btn btn-danger">
                <i class="fa fa-trash"></i> Delete
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>
@endif
@endsection

resources/views/thanks.blade.php
@extends('layout')

{{-- このようにcontainerとは、コンテンツを真ん中に配置する為の大きな枠という役割を持っている。 --}}
@section('content')
<div class="container d-flex align-items-cebter main">
  <div class="border p-4">
    <h1 class="h5 mb-4 text-warning ">
      ありがとうございます。今後参考にさせて頂きます。
    </h1>
  </div>
  <div class="mt-5 ml-4">
    <a class="btn btn-secondary" href="{{ route('top') }}">
      トップページに戻る
    </a>
  </div>
</div>
@endsection

<style>
  .main {
    margin-top: 80px;
  }
</style>